@startuml
actor       管理者       as admin
actor       ユーザー       as user
participant      システム      as sys
admin -> sys : 買取したい商品を登録
user -> sys : 買取対象を問い合わせ
sys --> user : 買取対象を返却
user -> sys : 買取希望を作成
sys -> admin : 買取希望の作成を通知
admin -> sys: 買取希望を問い合わせ
sys --> admin: 買取希望を返却
admin -> sys: 買取希望のステータスを「承認済み」に変更
sys -> user: 買取希望のステータス変更を通知
user -> sys: 商品の発送後にステータスを「発送済み」に変更
sys -> admin: 商品のステータス変更を通知
admin -> sys: 商品到着と支払い後にステータスを「完了」に変更
sys -> user: 買取希望のステータス変更を通知
@enduml
